# Generated by Django 3.1.2 on 2020-10-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myworkdata',
            name='image',
            field=models.ImageField(default='', upload_to='work/images'),
        ),
    ]
